#!/usr/bin/env python3
"""Generate/check Rust residue geometry from the immutable native header."""

import argparse
import os
from pathlib import Path
import shlex
import tempfile

from reference import BASELINE, HERE, ROOT, run, sha256


def generate():
    source = "datafusion/bio-format-foldcomp/native/vendor/amino_acid.h"
    header = run(["git", "show", f"{BASELINE}:{source}"], cwd=ROOT).stdout
    compiler = shlex.split(os.environ.get("CXX", "c++"))
    with tempfile.TemporaryDirectory(prefix="foldcomp-tables-") as directory:
        temp = Path(directory)
        (temp / "amino_acid.h").write_bytes(header)
        driver = HERE / "export_foldcomp_tables.cpp"
        msvc = Path(compiler[0]).name.lower() in ("cl", "cl.exe")
        executable = temp / ("tables.exe" if msvc else "tables")
        flags = (
            ["/nologo", "/std:c++17", "/EHsc", f"/I{temp}", f"/Fe{executable}"]
            if msvc
            else ["-std=c++17", "-I", str(temp), "-o", str(executable)]
        )
        run([*compiler, *flags, str(driver)], cwd=temp)
        rows = run([str(executable)], cwd=temp).stdout.decode().splitlines()
    lines = [
        "//! Generated by testing/oracles/structure-codecs/foldcomp_tables.py.",
        "//! Adapted from Foldcomp (MIT); see LICENSE-FOLDCOMP.",
        f"//! Formats revision: {BASELINE}",
        f"//! amino_acid.h SHA256: {sha256(header)}",
        "",
        "pub(super) struct SideAtom {",
        "    pub name: &'static str,",
        "    pub previous: [usize; 3],",
        "    pub length: f32,",
        "    pub angle: f32,",
        "}",
        "",
        "pub(super) const TABLES: [&[SideAtom]; 21] = [",
    ]
    first = True
    for row in rows:
        fields = row.split()
        if len(fields) == 1:
            if not first:
                lines.append("    ],")
            first = False
            lines.append(f"    &[ // {row}")
        else:
            name, a, b, c, length, angle = fields
            lines.extend(
                [
                    "        SideAtom {",
                    f'            name: "{name}",',
                    f"            previous: [{a}, {b}, {c}],",
                    f"            length: f32::from_bits({length}),",
                    f"            angle: f32::from_bits({angle}),",
                    "        },",
                ]
            )
    lines.extend(["    ],", "];", ""])
    # Use the repository formatter so --check also checks the committed form.
    return run(
        ["rustfmt", "--edition", "2024", "--emit", "stdout"],
        input="\n".join(lines).encode(),
        cwd=ROOT,
    ).stdout


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    modes = parser.add_mutually_exclusive_group(required=True)
    modes.add_argument("--record", action="store_true")
    modes.add_argument("--check", action="store_true")
    args = parser.parse_args()
    result = generate()
    path = ROOT / "datafusion/bio-format-foldcomp/src/fcz/tables.rs"
    if args.record:
        path.write_bytes(result)
    elif path.read_bytes() != result:
        parser.exit(1, "Rust residue tables differ from pinned source\n")
    print(
        "Verified 20 residue geometry tables and UNK"
        if args.check
        else "Generated Rust residue tables"
    )


if __name__ == "__main__":
    main()
