// Regression tests for multi-member gzip GFF files (issue #207).
// Fixtures are generated by scripts/gen_multimember_gz_fixtures.py and decode to
// 100 features (clean/split) or 2000 (pigz) only when every gzip member is read.
// GFF has both a sync and an async local gz reader; both were fixed.
use datafusion::prelude::*;
use datafusion_bio_format_core::object_storage::ObjectStorageOptions;
use datafusion_bio_format_gff::table_provider::GffTableProvider;
use std::sync::Arc;

async fn count_records(file: &str) -> usize {
    let path = format!("{}/tests/{}", env!("CARGO_MANIFEST_DIR"), file);
    // GFF's physical exec requires object storage options; AUTO detects gzip.
    let provider =
        GffTableProvider::new(path, None, Some(ObjectStorageOptions::default()), true).unwrap();
    let ctx = SessionContext::new();
    ctx.register_table("gff", Arc::new(provider)).unwrap();
    let batches = ctx
        .sql("SELECT chrom FROM gff")
        .await
        .unwrap()
        .collect()
        .await
        .unwrap();
    batches.iter().map(|b| b.num_rows()).sum()
}

#[tokio::test]
async fn multimember_clean_boundary_reads_all_members() {
    assert_eq!(
        count_records("multimember_clean.gff3.gz").await,
        100,
        "must decode all gzip members, not just the first"
    );
}

#[tokio::test]
async fn multimember_split_record_boundary_reads_all_members() {
    assert_eq!(
        count_records("multimember_split.gff3.gz").await,
        100,
        "must not lose data or crash on a mid-record gzip member boundary"
    );
}

#[tokio::test]
async fn multimember_pigz_concatenated_reads_all_members() {
    assert_eq!(
        count_records("multimember_pigz.gff3.gz").await,
        2000,
        "must decode all pigz members of a concatenated gzip stream"
    );
}
