//! Generated by testing/oracles/structure-codecs/foldcomp_tables.py.
//! Adapted from Foldcomp (MIT); see LICENSE-FOLDCOMP.
//! Formats revision: fd17754c55c63394717967c18b7a45cf8aeb48ee
//! amino_acid.h SHA256: 2506c06536df52562c9b65807e20b1ea343b075834d8f1eb1edd0d8f785fdec4

pub(super) struct SideAtom {
    pub name: &'static str,
    pub previous: [usize; 3],
    pub length: f32,
    pub angle: f32,
}

pub(super) const TABLES: [&[SideAtom]; 21] = [
    &[
        // ALA
        SideAtom {
            name: "O",
            previous: [0, 1, 2],
            length: f32::from_bits(1067282596),
            angle: f32::from_bits(1123065528),
        },
        SideAtom {
            name: "CB",
            previous: [3, 2, 1],
            length: f32::from_bits(1069715292),
            angle: f32::from_bits(1121825849),
        },
    ],
    &[
        // ARG
        SideAtom {
            name: "O",
            previous: [0, 1, 2],
            length: f32::from_bits(1067282596),
            angle: f32::from_bits(1122991473),
        },
        SideAtom {
            name: "CB",
            previous: [3, 2, 1],
            length: f32::from_bits(1069799178),
            angle: f32::from_bits(1121790067),
        },
        SideAtom {
            name: "CG",
            previous: [0, 1, 4],
            length: f32::from_bits(1069799178),
            angle: f32::from_bits(1122137932),
        },
        SideAtom {
            name: "CD",
            previous: [1, 4, 5],
            length: f32::from_bits(1069715292),
            angle: f32::from_bits(1121817330),
        },
        SideAtom {
            name: "NE",
            previous: [4, 5, 6],
            length: f32::from_bits(1069211976),
            angle: f32::from_bits(1121965703),
        },
        SideAtom {
            name: "CZ",
            previous: [5, 6, 7],
            length: f32::from_bits(1068037571),
            angle: f32::from_bits(1123705422),
        },
        SideAtom {
            name: "NH1",
            previous: [6, 7, 8],
            length: f32::from_bits(1067953684),
            angle: f32::from_bits(1123034989),
        },
        SideAtom {
            name: "NH2",
            previous: [6, 7, 8],
            length: f32::from_bits(1067953684),
            angle: f32::from_bits(1123034989),
        },
    ],
    &[
        // ASN
        SideAtom {
            name: "O",
            previous: [0, 1, 2],
            length: f32::from_bits(1067282596),
            angle: f32::from_bits(1123065922),
        },
        SideAtom {
            name: "CB",
            previous: [3, 2, 1],
            length: f32::from_bits(1069715292),
            angle: f32::from_bits(1121825849),
        },
        SideAtom {
            name: "CG",
            previous: [0, 1, 4],
            length: f32::from_bits(1069715292),
            angle: f32::from_bits(1122137801),
        },
        SideAtom {
            name: "OD1",
            previous: [1, 4, 5],
            length: f32::from_bits(1067282596),
            angle: f32::from_bits(1123136307),
        },
        SideAtom {
            name: "ND2",
            previous: [1, 4, 5],
            length: f32::from_bits(1068079514),
            angle: f32::from_bits(1122563523),
        },
    ],
    &[
        // ASP
        SideAtom {
            name: "O",
            previous: [0, 1, 2],
            length: f32::from_bits(1067282596),
            angle: f32::from_bits(1123162653),
        },
        SideAtom {
            name: "CB",
            previous: [3, 2, 1],
            length: f32::from_bits(1069799178),
            angle: f32::from_bits(1121828340),
        },
        SideAtom {
            name: "CG",
            previous: [0, 1, 4],
            length: f32::from_bits(1069715292),
            angle: f32::from_bits(1122137801),
        },
        SideAtom {
            name: "OD1",
            previous: [1, 4, 5],
            length: f32::from_bits(1067433591),
            angle: f32::from_bits(1122807841),
        },
        SideAtom {
            name: "OD2",
            previous: [1, 4, 5],
            length: f32::from_bits(1067433591),
            angle: f32::from_bits(1122807841),
        },
    ],
    &[
        // CYS
        SideAtom {
            name: "O",
            previous: [0, 1, 2],
            length: f32::from_bits(1067282596),
            angle: f32::from_bits(1123033154),
        },
        SideAtom {
            name: "CB",
            previous: [3, 2, 1],
            length: f32::from_bits(1069799178),
            angle: f32::from_bits(1121855472),
        },
        SideAtom {
            name: "SG",
            previous: [0, 1, 4],
            length: f32::from_bits(1072064102),
            angle: f32::from_bits(1122214478),
        },
    ],
    &[
        // GLN
        SideAtom {
            name: "O",
            previous: [0, 1, 2],
            length: f32::from_bits(1067282596),
            angle: f32::from_bits(1123052552),
        },
        SideAtom {
            name: "CB",
            previous: [3, 2, 1],
            length: f32::from_bits(1069799178),
            angle: f32::from_bits(1121648640),
        },
        SideAtom {
            name: "CG",
            previous: [0, 1, 4],
            length: f32::from_bits(1069715292),
            angle: f32::from_bits(1122145665),
        },
        SideAtom {
            name: "CD",
            previous: [1, 4, 5],
            length: f32::from_bits(1069715292),
            angle: f32::from_bits(1122082619),
        },
        SideAtom {
            name: "OE1",
            previous: [4, 5, 6],
            length: f32::from_bits(1067282596),
            angle: f32::from_bits(1123266593),
        },
        SideAtom {
            name: "NE2",
            previous: [4, 5, 6],
            length: f32::from_bits(1068037571),
            angle: f32::from_bits(1122566144),
        },
    ],
    &[
        // GLU
        SideAtom {
            name: "O",
            previous: [0, 1, 2],
            length: f32::from_bits(1067282596),
            angle: f32::from_bits(1123102753),
        },
        SideAtom {
            name: "CB",
            previous: [3, 2, 1],
            length: f32::from_bits(1069799178),
            angle: f32::from_bits(1121784693),
        },
        SideAtom {
            name: "CG",
            previous: [0, 1, 4],
            length: f32::from_bits(1069715292),
            angle: f32::from_bits(1122214871),
        },
        SideAtom {
            name: "CD",
            previous: [1, 4, 5],
            length: f32::from_bits(1069715292),
            angle: f32::from_bits(1122095858),
        },
        SideAtom {
            name: "OE1",
            previous: [4, 5, 6],
            length: f32::from_bits(1067450368),
            angle: f32::from_bits(1122825535),
        },
        SideAtom {
            name: "OE2",
            previous: [4, 5, 6],
            length: f32::from_bits(1067450368),
            angle: f32::from_bits(1122825535),
        },
    ],
    &[
        // GLY
        SideAtom {
            name: "O",
            previous: [0, 1, 2],
            length: f32::from_bits(1067282596),
            angle: f32::from_bits(1123093316),
        },
    ],
    &[
        // HIS
        SideAtom {
            name: "O",
            previous: [0, 1, 2],
            length: f32::from_bits(1067282596),
            angle: f32::from_bits(1123096723),
        },
        SideAtom {
            name: "CB",
            previous: [3, 2, 1],
            length: f32::from_bits(1069799178),
            angle: f32::from_bits(1121888371),
        },
        SideAtom {
            name: "CG",
            previous: [0, 1, 4],
            length: f32::from_bits(1069547520),
            angle: f32::from_bits(1122168734),
        },
        SideAtom {
            name: "ND1",
            previous: [1, 4, 5],
            length: f32::from_bits(1068540887),
            angle: f32::from_bits(1123398451),
        },
        SideAtom {
            name: "CD2",
            previous: [1, 4, 5],
            length: f32::from_bits(1068373115),
            angle: f32::from_bits(1124244521),
        },
        SideAtom {
            name: "CE1",
            previous: [4, 5, 6],
            length: f32::from_bits(1068121457),
            angle: f32::from_bits(1121529233),
        },
        SideAtom {
            name: "NE2",
            previous: [4, 5, 7],
            length: f32::from_bits(1068540887),
            angle: f32::from_bits(1121378501),
        },
    ],
    &[
        // ILE
        SideAtom {
            name: "O",
            previous: [0, 1, 2],
            length: f32::from_bits(1067324539),
            angle: f32::from_bits(1123076407),
        },
        SideAtom {
            name: "CB",
            previous: [3, 2, 1],
            length: f32::from_bits(1069883064),
            angle: f32::from_bits(1121974092),
        },
        SideAtom {
            name: "CG1",
            previous: [0, 1, 4],
            length: f32::from_bits(1069799178),
            angle: f32::from_bits(1121779712),
        },
        SideAtom {
            name: "CG2",
            previous: [0, 1, 4],
            length: f32::from_bits(1069715292),
            angle: f32::from_bits(1121779712),
        },
        SideAtom {
            name: "CD1",
            previous: [1, 4, 5],
            length: f32::from_bits(1069631406),
            angle: f32::from_bits(1122234532),
        },
    ],
    &[
        // LEU
        SideAtom {
            name: "O",
            previous: [0, 1, 2],
            length: f32::from_bits(1067324539),
            angle: f32::from_bits(1123052552),
        },
        SideAtom {
            name: "CB",
            previous: [3, 2, 1],
            length: f32::from_bits(1069799178),
            angle: f32::from_bits(1121768964),
        },
        SideAtom {
            name: "CG",
            previous: [0, 1, 4],
            length: f32::from_bits(1069799178),
            angle: f32::from_bits(1122513715),
        },
        SideAtom {
            name: "CD1",
            previous: [1, 4, 5],
            length: f32::from_bits(1069715292),
            angle: f32::from_bits(1121790198),
        },
        SideAtom {
            name: "CD2",
            previous: [1, 4, 5],
            length: f32::from_bits(1069715292),
            angle: f32::from_bits(1121790198),
        },
    ],
    &[
        // LYS
        SideAtom {
            name: "O",
            previous: [0, 1, 2],
            length: f32::from_bits(1067282596),
            angle: f32::from_bits(1123095675),
        },
        SideAtom {
            name: "CB",
            previous: [3, 2, 1],
            length: f32::from_bits(1069799178),
            angle: f32::from_bits(1121648640),
        },
        SideAtom {
            name: "CG",
            previous: [0, 1, 4],
            length: f32::from_bits(1069715292),
            angle: f32::from_bits(1122216182),
        },
        SideAtom {
            name: "CD",
            previous: [1, 4, 5],
            length: f32::from_bits(1069715292),
            angle: f32::from_bits(1121948795),
        },
        SideAtom {
            name: "CE",
            previous: [4, 5, 6],
            length: f32::from_bits(1069715292),
            angle: f32::from_bits(1121948795),
        },
        SideAtom {
            name: "NZ",
            previous: [5, 6, 7],
            length: f32::from_bits(1069463634),
            angle: f32::from_bits(1122009088),
        },
    ],
    &[
        // MET
        SideAtom {
            name: "O",
            previous: [0, 1, 2],
            length: f32::from_bits(1067282596),
            angle: f32::from_bits(1123044295),
        },
        SideAtom {
            name: "CB",
            previous: [3, 2, 1],
            length: f32::from_bits(1069799178),
            angle: f32::from_bits(1121823359),
        },
        SideAtom {
            name: "CG",
            previous: [0, 1, 4],
            length: f32::from_bits(1069715292),
            angle: f32::from_bits(1122196521),
        },
        SideAtom {
            name: "SD",
            previous: [1, 4, 5],
            length: f32::from_bits(1072064102),
            angle: f32::from_bits(1122077639),
        },
        SideAtom {
            name: "CE",
            previous: [4, 5, 6],
            length: f32::from_bits(1071980216),
            angle: f32::from_bits(1120483410),
        },
    ],
    &[
        // PHE
        SideAtom {
            name: "O",
            previous: [0, 1, 2],
            length: f32::from_bits(1067282596),
            angle: f32::from_bits(1123061989),
        },
        SideAtom {
            name: "CB",
            previous: [3, 2, 1],
            length: f32::from_bits(1069799178),
            angle: f32::from_bits(1121825063),
        },
        SideAtom {
            name: "CG",
            previous: [0, 1, 4],
            length: f32::from_bits(1069631406),
            angle: f32::from_bits(1122238464),
        },
        SideAtom {
            name: "CD1",
            previous: [1, 4, 5],
            length: f32::from_bits(1068582830),
            angle: f32::from_bits(1123024896),
        },
        SideAtom {
            name: "CD2",
            previous: [1, 4, 5],
            length: f32::from_bits(1068582830),
            angle: f32::from_bits(1123024896),
        },
        SideAtom {
            name: "CE1",
            previous: [4, 5, 6],
            length: f32::from_bits(1068582830),
            angle: f32::from_bits(1123024896),
        },
        SideAtom {
            name: "CE2",
            previous: [4, 5, 7],
            length: f32::from_bits(1068582830),
            angle: f32::from_bits(1123024896),
        },
        SideAtom {
            name: "CZ",
            previous: [5, 6, 8],
            length: f32::from_bits(1068582830),
            angle: f32::from_bits(1123024896),
        },
    ],
    &[
        // PRO
        SideAtom {
            name: "O",
            previous: [0, 1, 2],
            length: f32::from_bits(1067282596),
            angle: f32::from_bits(1123103539),
        },
        SideAtom {
            name: "CB",
            previous: [3, 2, 1],
            length: f32::from_bits(1069799178),
            angle: f32::from_bits(1121894007),
        },
        SideAtom {
            name: "CG",
            previous: [0, 1, 4],
            length: f32::from_bits(1069463634),
            angle: f32::from_bits(1120955269),
        },
        SideAtom {
            name: "CD",
            previous: [1, 4, 5],
            length: f32::from_bits(1069547520),
            angle: f32::from_bits(1121058816),
        },
    ],
    &[
        // SER
        SideAtom {
            name: "O",
            previous: [0, 1, 2],
            length: f32::from_bits(1067282596),
            angle: f32::from_bits(1123087155),
        },
        SideAtom {
            name: "CB",
            previous: [3, 2, 1],
            length: f32::from_bits(1069799178),
            angle: f32::from_bits(1121746682),
        },
        SideAtom {
            name: "OG",
            previous: [0, 1, 4],
            length: f32::from_bits(1068851266),
            angle: f32::from_bits(1121862550),
        },
    ],
    &[
        // THR
        SideAtom {
            name: "O",
            previous: [0, 1, 2],
            length: f32::from_bits(1067282596),
            angle: f32::from_bits(1123057926),
        },
        SideAtom {
            name: "CB",
            previous: [3, 2, 1],
            length: f32::from_bits(1069799178),
            angle: f32::from_bits(1121724006),
        },
        SideAtom {
            name: "OG1",
            previous: [0, 1, 4],
            length: f32::from_bits(1068960317),
            angle: f32::from_bits(1121641038),
        },
        SideAtom {
            name: "CG2",
            previous: [0, 1, 4],
            length: f32::from_bits(1069715292),
            angle: f32::from_bits(1121905148),
        },
    ],
    &[
        // TRP
        SideAtom {
            name: "O",
            previous: [0, 1, 2],
            length: f32::from_bits(1067282596),
            angle: f32::from_bits(1123048227),
        },
        SideAtom {
            name: "CB",
            previous: [3, 2, 1],
            length: f32::from_bits(1069799178),
            angle: f32::from_bits(1121825849),
        },
        SideAtom {
            name: "CG",
            previous: [0, 1, 4],
            length: f32::from_bits(1069547520),
            angle: f32::from_bits(1122251571),
        },
        SideAtom {
            name: "CD1",
            previous: [1, 4, 5],
            length: f32::from_bits(1068373115),
            angle: f32::from_bits(1123904651),
        },
        SideAtom {
            name: "CD2",
            previous: [1, 4, 5],
            length: f32::from_bits(1069044204),
            angle: f32::from_bits(1123904651),
        },
        SideAtom {
            name: "NE1",
            previous: [4, 5, 6],
            length: f32::from_bits(1068540887),
            angle: f32::from_bits(1121708802),
        },
        SideAtom {
            name: "CE2",
            previous: [4, 5, 7],
            length: f32::from_bits(1068792545),
            angle: f32::from_bits(1121431323),
        },
        SideAtom {
            name: "CE3",
            previous: [4, 5, 7],
            length: f32::from_bits(1068708659),
            angle: f32::from_bits(1124465050),
        },
        SideAtom {
            name: "CZ2",
            previous: [5, 7, 9],
            length: f32::from_bits(1068708659),
            angle: f32::from_bits(1123024896),
        },
        SideAtom {
            name: "CZ3",
            previous: [5, 7, 10],
            length: f32::from_bits(1068574441),
            angle: f32::from_bits(1123024896),
        },
        SideAtom {
            name: "CH2",
            previous: [7, 9, 11],
            length: f32::from_bits(1068431835),
            angle: f32::from_bits(1123024896),
        },
    ],
    &[
        // TYR
        SideAtom {
            name: "O",
            previous: [0, 1, 2],
            length: f32::from_bits(1067324539),
            angle: f32::from_bits(1123104588),
        },
        SideAtom {
            name: "CB",
            previous: [3, 2, 1],
            length: f32::from_bits(1069799178),
            angle: f32::from_bits(1121825849),
        },
        SideAtom {
            name: "CG",
            previous: [0, 1, 4],
            length: f32::from_bits(1069631406),
            angle: f32::from_bits(1122204910),
        },
        SideAtom {
            name: "CD1",
            previous: [1, 4, 5],
            length: f32::from_bits(1068624773),
            angle: f32::from_bits(1123147710),
        },
        SideAtom {
            name: "CD2",
            previous: [1, 4, 5],
            length: f32::from_bits(1068624773),
            angle: f32::from_bits(1123147710),
        },
        SideAtom {
            name: "CE1",
            previous: [4, 5, 6],
            length: f32::from_bits(1068540887),
            angle: f32::from_bits(1123024896),
        },
        SideAtom {
            name: "CE2",
            previous: [4, 5, 7],
            length: f32::from_bits(1068540887),
            angle: f32::from_bits(1123024896),
        },
        SideAtom {
            name: "CZ",
            previous: [5, 6, 8],
            length: f32::from_bits(1068524110),
            angle: f32::from_bits(1123024896),
        },
        SideAtom {
            name: "OH",
            previous: [6, 8, 10],
            length: f32::from_bits(1068498944),
            angle: f32::from_bits(1123024896),
        },
    ],
    &[
        // VAL
        SideAtom {
            name: "O",
            previous: [0, 1, 2],
            length: f32::from_bits(1067324539),
            angle: f32::from_bits(1123086762),
        },
        SideAtom {
            name: "CB",
            previous: [3, 2, 1],
            length: f32::from_bits(1069883064),
            angle: f32::from_bits(1121895186),
        },
        SideAtom {
            name: "CG1",
            previous: [0, 1, 4],
            length: f32::from_bits(1069715292),
            angle: f32::from_bits(1121805926),
        },
        SideAtom {
            name: "CG2",
            previous: [0, 1, 4],
            length: f32::from_bits(1069715292),
            angle: f32::from_bits(1121766605),
        },
    ],
    &[ // UNK
    ],
];
