//! Integration tests against fixtures generated by the reference `cooler`
//! implementation (`tests/data/generate_fixtures.py`).
//!
//! Known fixture facts (printed by the generator and cross-checked with
//! `cooler.Cooler`): test.cool has nnz=4210, chroms chr1:100000/chr2:60000 at
//! 1 kb bins, and its first pixels are (0,0,72), (0,2,6), (0,3,93);
//! test.mcool stores balanced resolutions 1000/2000/5000 with nnz=2560 at
//! 2 kb; test_float.cool stores float64 counts 36.0, 3.0, 46.5.

use std::sync::Arc;

use datafusion::arrow::array::{
    Array, Float64Array, Int32Array, Int64Array, RecordBatch, StringArray, UInt32Array,
};
use datafusion::arrow::datatypes::DataType;
use datafusion::prelude::{SessionConfig, SessionContext};
use datafusion_bio_format_cooler::{CoolerTableProvider, list_data_collections};

fn fixture(name: &str) -> String {
    format!("{}/tests/data/{name}", env!("CARGO_MANIFEST_DIR"))
}

fn provider(
    path: &str,
    resolution: Option<u64>,
    join_bins: bool,
    include_weights: bool,
    zero_based: bool,
) -> CoolerTableProvider {
    CoolerTableProvider::new(
        path.to_string(),
        resolution,
        join_bins,
        include_weights,
        zero_based,
    )
    .expect("provider opens")
}

async fn collect(provider: CoolerTableProvider, sql: &str, partitions: usize) -> Vec<RecordBatch> {
    let config = SessionConfig::new().with_target_partitions(partitions);
    let ctx = SessionContext::new_with_config(config);
    ctx.register_table("c", Arc::new(provider)).unwrap();
    ctx.sql(sql).await.unwrap().collect().await.unwrap()
}

fn total_rows(batches: &[RecordBatch]) -> usize {
    batches.iter().map(RecordBatch::num_rows).sum()
}

#[tokio::test]
async fn full_scan_joined_one_based() {
    let batches = collect(
        provider(&fixture("test.cool"), None, true, false, false),
        "SELECT * FROM c",
        1,
    )
    .await;
    assert_eq!(total_rows(&batches), 4210);
    let batch = &batches[0];
    assert_eq!(batch.schema().field(0).name(), "chrom1");
    let chrom1 = batch
        .column(0)
        .as_any()
        .downcast_ref::<StringArray>()
        .unwrap();
    let start1 = batch
        .column(1)
        .as_any()
        .downcast_ref::<UInt32Array>()
        .unwrap();
    let end1 = batch
        .column(2)
        .as_any()
        .downcast_ref::<UInt32Array>()
        .unwrap();
    let chrom2 = batch
        .column(3)
        .as_any()
        .downcast_ref::<StringArray>()
        .unwrap();
    let start2 = batch
        .column(4)
        .as_any()
        .downcast_ref::<UInt32Array>()
        .unwrap();
    let count = batch
        .column(6)
        .as_any()
        .downcast_ref::<Int32Array>()
        .unwrap();
    // first pixel: bins (0,0) -> chr1:0-1000 x chr1:0-1000, count 72; 1-based start = 1
    assert_eq!(chrom1.value(0), "chr1");
    assert_eq!(start1.value(0), 1);
    assert_eq!(end1.value(0), 1000);
    assert_eq!(chrom2.value(0), "chr1");
    assert_eq!(start2.value(0), 1);
    assert_eq!(count.value(0), 72);
    // second pixel: bins (0,2) -> chrom2 bin start 2000 (1-based 2001), count 6
    assert_eq!(start2.value(1), 2001);
    assert_eq!(count.value(1), 6);
}

#[tokio::test]
async fn full_scan_zero_based() {
    let batches = collect(
        provider(&fixture("test.cool"), None, true, false, true),
        "SELECT * FROM c",
        1,
    )
    .await;
    let batch = &batches[0];
    let start1 = batch
        .column(1)
        .as_any()
        .downcast_ref::<UInt32Array>()
        .unwrap();
    let end1 = batch
        .column(2)
        .as_any()
        .downcast_ref::<UInt32Array>()
        .unwrap();
    assert_eq!(start1.value(0), 0);
    assert_eq!(end1.value(0), 1000);
}

#[tokio::test]
async fn raw_coo_mode() {
    let batches = collect(
        provider(&fixture("test.cool"), None, false, false, false),
        "SELECT * FROM c",
        1,
    )
    .await;
    let batch = &batches[0];
    assert_eq!(batch.schema().field(0).name(), "bin1_id");
    let bin1 = batch
        .column(0)
        .as_any()
        .downcast_ref::<Int64Array>()
        .unwrap();
    let bin2 = batch
        .column(1)
        .as_any()
        .downcast_ref::<Int64Array>()
        .unwrap();
    let count = batch
        .column(2)
        .as_any()
        .downcast_ref::<Int32Array>()
        .unwrap();
    assert_eq!((bin1.value(0), bin2.value(0), count.value(0)), (0, 0, 72));
    assert_eq!((bin1.value(1), bin2.value(1), count.value(1)), (0, 2, 6));
}

#[tokio::test]
async fn mcool_resolution_and_uri() {
    let by_argument = collect(
        provider(&fixture("test.mcool"), Some(2000), true, false, false),
        "SELECT * FROM c",
        1,
    )
    .await;
    assert_eq!(total_rows(&by_argument), 2560);
    let by_uri = collect(
        provider(
            &format!("{}::/resolutions/2000", fixture("test.mcool")),
            None,
            true,
            false,
            false,
        ),
        "SELECT * FROM c",
        1,
    )
    .await;
    assert_eq!(total_rows(&by_uri), 2560);
}

#[test]
fn mcool_without_resolution_errors_listing_available() {
    let error = CoolerTableProvider::new(fixture("test.mcool"), None, true, false, false)
        .unwrap_err()
        .to_string();
    assert!(
        error.contains("1000") && error.contains("2000") && error.contains("5000"),
        "{error}"
    );
}

#[test]
fn mcool_missing_resolution_errors() {
    let error = CoolerTableProvider::new(fixture("test.mcool"), Some(1234), true, false, false)
        .unwrap_err()
        .to_string();
    assert!(
        error.contains("1234") && error.contains("available"),
        "{error}"
    );
}

#[test]
fn conflicting_uri_and_resolution_errors() {
    let error = CoolerTableProvider::new(
        format!("{}::/resolutions/2000", fixture("test.mcool")),
        Some(5000),
        true,
        false,
        false,
    )
    .unwrap_err()
    .to_string();
    assert!(error.contains("Conflicting"), "{error}");
}

#[test]
fn remote_path_rejected() {
    let error = CoolerTableProvider::new(
        "s3://bucket/contacts.cool".to_string(),
        None,
        true,
        false,
        false,
    )
    .unwrap_err()
    .to_string();
    assert!(error.contains("local filesystem"), "{error}");
}

#[tokio::test]
async fn float_count_dtype() {
    let batches = collect(
        provider(&fixture("test_float.cool"), None, true, false, false),
        "SELECT count FROM c",
        1,
    )
    .await;
    let batch = &batches[0];
    assert_eq!(batch.schema().field(0).data_type(), &DataType::Float64);
    let count = batch
        .column(0)
        .as_any()
        .downcast_ref::<Float64Array>()
        .unwrap();
    assert_eq!(count.value(0), 36.0);
    assert_eq!(count.value(2), 46.5);
}

#[tokio::test]
async fn weights_exposed_on_balanced_mcool() {
    let batches = collect(
        provider(&fixture("test.mcool"), Some(2000), true, true, false),
        "SELECT weight1, weight2 FROM c",
        1,
    )
    .await;
    let batch = &batches[0];
    let weight1 = batch
        .column(0)
        .as_any()
        .downcast_ref::<Float64Array>()
        .unwrap();
    assert!(weight1.value(0).is_finite());
}

#[test]
fn weights_missing_errors() {
    let error = CoolerTableProvider::new(fixture("test.cool"), None, true, true, false)
        .unwrap_err()
        .to_string();
    assert!(error.contains("bins/weight"), "{error}");
}

#[tokio::test]
async fn count_star_and_projection() {
    let batches = collect(
        provider(&fixture("test.cool"), None, true, false, false),
        "SELECT count(*) AS n FROM c",
        1,
    )
    .await;
    let n = batches[0]
        .column(0)
        .as_any()
        .downcast_ref::<Int64Array>()
        .unwrap();
    assert_eq!(n.value(0), 4210);

    let batches = collect(
        provider(&fixture("test.cool"), None, true, false, false),
        "SELECT chrom1, count FROM c",
        1,
    )
    .await;
    assert_eq!(batches[0].num_columns(), 2);
    assert_eq!(total_rows(&batches), 4210);
}

#[tokio::test]
async fn partitioned_scan_matches_single_partition() {
    let single = collect(
        provider(&fixture("test.cool"), None, true, false, false),
        "SELECT sum(count) AS s, count(*) AS n FROM c",
        1,
    )
    .await;
    let parallel = collect(
        provider(&fixture("test.cool"), None, true, false, false),
        "SELECT sum(count) AS s, count(*) AS n FROM c",
        4,
    )
    .await;
    let value = |batches: &[RecordBatch], col: usize| -> i64 {
        batches[0]
            .column(col)
            .as_any()
            .downcast_ref::<Int64Array>()
            .unwrap()
            .value(0)
    };
    assert_eq!(value(&single, 0), value(&parallel, 0));
    assert_eq!(value(&single, 1), value(&parallel, 1));
    assert_eq!(value(&single, 1), 4210);
}

#[test]
fn list_collections_cool_and_mcool() {
    let cool = list_data_collections(&fixture("test.cool")).unwrap();
    assert_eq!(cool.len(), 1);
    assert_eq!(cool[0].bin_size, Some(1000));
    assert_eq!(cool[0].nnz, Some(4210));
    assert_eq!(cool[0].nchroms, 2);
    assert_eq!(cool[0].assembly.as_deref(), Some("toyGenome"));

    let mcool = list_data_collections(&fixture("test.mcool")).unwrap();
    assert_eq!(mcool.len(), 3);
    assert_eq!(
        mcool
            .iter()
            .map(|c| c.bin_size.unwrap())
            .collect::<Vec<_>>(),
        vec![1000, 2000, 5000]
    );
}
