// Regression tests for multi-member gzip Pairs files (issue #207).
// Fixtures are generated by scripts/gen_multimember_gz_fixtures.py and decode to
// 100 pairs (clean/split) or 2000 (pigz) only when every gzip member is read.
use datafusion::prelude::*;
use datafusion_bio_format_pairs::table_provider::PairsTableProvider;
use std::sync::Arc;

async fn count_records(file: &str) -> usize {
    let path = format!("{}/tests/{}", env!("CARGO_MANIFEST_DIR"), file);
    // Pairs coordinates are 1-based; matches the existing indexed gz test.
    let provider = PairsTableProvider::new(path, None, false).unwrap();
    let ctx = SessionContext::new();
    ctx.register_table("pairs", Arc::new(provider)).unwrap();
    let batches = ctx
        .sql("SELECT chr1 FROM pairs")
        .await
        .unwrap()
        .collect()
        .await
        .unwrap();
    batches.iter().map(|b| b.num_rows()).sum()
}

#[tokio::test]
async fn multimember_clean_boundary_reads_all_members() {
    assert_eq!(
        count_records("multimember_clean.pairs.gz").await,
        100,
        "must decode all gzip members, not just the first"
    );
}

#[tokio::test]
async fn multimember_split_record_boundary_reads_all_members() {
    assert_eq!(
        count_records("multimember_split.pairs.gz").await,
        100,
        "must not lose data or crash on a mid-record gzip member boundary"
    );
}

#[tokio::test]
async fn multimember_pigz_concatenated_reads_all_members() {
    assert_eq!(
        count_records("multimember_pigz.pairs.gz").await,
        2000,
        "must decode all pigz members of a concatenated gzip stream"
    );
}
