// Regression tests for multi-member gzip VCF files (issue #207).
// Fixtures are generated by scripts/gen_multimember_gz_fixtures.py and decode to
// 100 variants (clean/split) or 2000 (pigz) only when every gzip member is read.
use datafusion::prelude::*;
use datafusion_bio_format_vcf::table_provider::VcfTableProvider;
use std::sync::Arc;

async fn count_records(file: &str) -> usize {
    let path = format!("{}/tests/{}", env!("CARGO_MANIFEST_DIR"), file);
    let provider = VcfTableProvider::new(path, None, None, None, true).unwrap();
    let ctx = SessionContext::new();
    ctx.register_table("vcf", Arc::new(provider)).unwrap();
    let batches = ctx
        .sql("SELECT chrom FROM vcf")
        .await
        .unwrap()
        .collect()
        .await
        .unwrap();
    batches.iter().map(|b| b.num_rows()).sum()
}

#[tokio::test]
async fn multimember_clean_boundary_reads_all_members() {
    assert_eq!(
        count_records("multimember_clean.vcf.gz").await,
        100,
        "must decode all gzip members, not just the first"
    );
}

#[tokio::test]
async fn multimember_split_record_boundary_reads_all_members() {
    assert_eq!(
        count_records("multimember_split.vcf.gz").await,
        100,
        "must not lose data or crash on a mid-record gzip member boundary"
    );
}

#[tokio::test]
async fn multimember_pigz_concatenated_reads_all_members() {
    assert_eq!(
        count_records("multimember_pigz.vcf.gz").await,
        2000,
        "must decode all pigz members of a concatenated gzip stream"
    );
}
