// Regression tests for multi-member gzip FASTA files (issue #207).
// Fixtures are generated by scripts/gen_multimember_gz_fixtures.py and decode to
// 100 sequences (clean/split) or 2000 (pigz) only when every gzip member is read.
use datafusion::prelude::*;
use datafusion_bio_format_core::object_storage::ObjectStorageOptions;
use datafusion_bio_format_fasta::table_provider::FastaTableProvider;
use std::sync::Arc;

async fn count_records(file: &str) -> usize {
    let path = format!("{}/tests/{}", env!("CARGO_MANIFEST_DIR"), file);
    // FASTA's physical exec requires object storage options; AUTO detects gzip.
    let provider = FastaTableProvider::new(path, Some(ObjectStorageOptions::default())).unwrap();
    let ctx = SessionContext::new();
    ctx.register_table("fasta", Arc::new(provider)).unwrap();
    let batches = ctx
        .sql("SELECT name FROM fasta")
        .await
        .unwrap()
        .collect()
        .await
        .unwrap();
    batches.iter().map(|b| b.num_rows()).sum()
}

#[tokio::test]
async fn multimember_clean_boundary_reads_all_members() {
    assert_eq!(
        count_records("multimember_clean.fasta.gz").await,
        100,
        "must decode all gzip members, not just the first"
    );
}

#[tokio::test]
async fn multimember_split_record_boundary_reads_all_members() {
    assert_eq!(
        count_records("multimember_split.fasta.gz").await,
        100,
        "must not lose data or crash on a mid-record gzip member boundary"
    );
}

#[tokio::test]
async fn multimember_pigz_concatenated_reads_all_members() {
    assert_eq!(
        count_records("multimember_pigz.fasta.gz").await,
        2000,
        "must decode all pigz members of a concatenated gzip stream"
    );
}
